### ISSUE TITLE
Uncaught TypeError: Cannot read property 'length' of undefined

### ISSUE THREAD

**Issue by ArhontSL** [Lazade/html-to-less#1]
[Enter steps to reproduce:]

1. ...
2. ...

**Atom**: 1.34.0 x64
**Electron**: 2.0.16
**OS**: Ubuntu 18.04.1
**Thrown From**: [html-to-less](https://github.com/Lazade/html-to-less) package 1.2.2

### Stack Trace

Uncaught TypeError: Cannot read property 'length' of undefined

```
At /home/arhont/.atom/packages/html-to-less/lib/facilitate.js:31

TypeError: Cannot read property 'length' of undefined
    at /packages/html-to-less/lib/facilitate.js:31:22
    at Array.forEach (<anonymous>)
    at recursive (/packages/html-to-less/lib/facilitate.js:30:11)
    at exports.facilitate (/packages/html-to-less/lib/facilitate.js:55:3)
    at Object.generate (/packages/html-to-less/lib/html-to-less.js:27:21)
    at HTMLElement.htmlToLessGenerate (/packages/html-to-less/lib/html-to-less.js:15:43)
    at CommandRegistry.handleCommandEvent (/snap/atom/210/usr/share/atom/resources/app/static/<embedded>:11:350055)
    at CommandRegistry.dispatch (/snap/atom/210/usr/share/atom/resources/app/static/<embedded>:11:348530)
    at AtomEnvironment.dispatchApplicationMenuCommand (/snap/atom/210/usr/share/atom/resources/app/static/<embedded>:1:669183)
    at EventEmitter.t (/snap/atom/210/usr/share/atom/resources/app/static/<embedded>:1:676567)
    at emitThree (events.js:136:13)
    at EventEmitter.emit (events.js:217:7)
```

### Commands

```
     -8:38.7.0 editor:select-to-end-of-line (input.hidden-input)
     -8:37.7.0 core:cut (input.hidden-input)
  2x -8:37.5.0 core:move-left (input.hidden-input)
     -8:37 core:paste (input.hidden-input)
 25x -8:35.9.0 core:move-left (input.hidden-input)
     -8:33.1.0 editor:move-to-end-of-screen-line (input.hidden-input)
     -8:33 emmet:expand-abbreviation-with-tab (input.hidden-input)
     -8:32.2.0 core:save (input.hidden-input)
     -5:20.1.0 core:paste (input.hidden-input)
     -3:34.7.0 core:select-all (input.hidden-input)
     -3:34.5.0 core:paste (input.hidden-input)
  2x -2:49.9.0 html-to-less:generate (div.panels-item)
  2x -1:53.7.0 application:add-project-folder (div.tool-panel.tree-view)
     -0:19.8.0 tree-view:remove-project-folder (span.name.icon.icon-file-directory)
     -0:08.3.0 core:move-down (input.hidden-input)
     -0:02.7.0 html-to-less:generate (input.hidden-input)
```

### Non-Core Packages

```
angular-2 0.2.6 
atom-beautify 0.33.4 
emmet 2.4.3 
html-to-less 1.2.2 
platformio-ide-terminal 2.8.4 
```

**Comment by litsazib** [comment]
issue mac os

**Comment by NaveenMetta** [comment]
[Enter steps to reproduce:]

1. ...
2. ...

**Atom**: 1.54.0 x64
**Electron**: 6.1.12
**OS**: macOS 11.2.1
**Thrown From**: [html-to-less](https://github.com/Lazade/html-to-less) package 1.2.2


### Stack Trace

Uncaught TypeError: Cannot read property 'length' of undefined

```
At /Users/naveenmetta/.atom/packages/html-to-less/lib/facilitate.js:31

TypeError: Cannot read property 'length' of undefined
    at /packages/html-to-less/lib/facilitate.js:31:22
    at Array.forEach (<anonymous>)
    at recursive (/packages/html-to-less/lib/facilitate.js:30:11)
    at /packages/html-to-less/lib/facilitate.js:40:7
    at Array.forEach (<anonymous>)
    at recursive (/packages/html-to-less/lib/facilitate.js:30:11)
    at /packages/html-to-less/lib/facilitate.js:40:7
    at Array.forEach (<anonymous>)
    at recursive (/packages/html-to-less/lib/facilitate.js:30:11)
    at /packages/html-to-less/lib/facilitate.js:40:7
    at Array.forEach (<anonymous>)
    at recursive (/packages/html-to-less/lib/facilitate.js:30:11)
    at exports.facilitate (/packages/html-to-less/lib/facilitate.js:55:3)
    at Object.generate (/packages/html-to-less/lib/html-to-less.js:27:21)
    at HTMLElement.htmlToLessGenerate (/packages/html-to-less/lib/html-to-less.js:15:43)
    at CommandRegistry.handleCommandEvent (/Applications/Atom.app/Contents/Resources/app/static/<embedded>:11:350382)
    at CommandRegistry.dispatch (/Applications/Atom.app/Contents/Resources/app/static/<embedded>:11:348857)
    at AtomEnvironment.dispatchContextMenuCommand (/Applications/Atom.app/Contents/Resources/app/static/<embedded>:1:727628)
    at EventEmitter.t (/Applications/Atom.app/Contents/Resources/app/static/<embedded>:1:735661)
    at EventEmitter.emit (events.js:200:13)
    at Object.onMessage (/Applications/Atom.app/Contents/Resources/electron.asar/renderer/init.js:42:16)
```

### Commands

```
     -7:41.3.0 html-to-less:generate (span.syntax--string.syntax--html)
     -7:28.9.0 editor:newline (input.hidden-input)
     -7:28.2.0 core:move-up (input.hidden-input)
  3x -7:13.2.0 editor:newline (input.hidden-input)
     -6:46.9.0 core:backspace (input.hidden-input)
  2x -6:38 html-to-less:generate (div.line)
     -5:12.6.0 core:undo (div.highlights)
     -4:56.6.0 html-to-less:generate (div.line)
     -4:09.6.0 pretty-html:toggle (div.line)
     -3:46.7.0 html-to-less:generate (div.line)
```

### Non-Core Packages

```
atom-material-ui 2.1.3 
autocomplete-html-entities 0.2.0 
autocomplete-json 5.5.5 
colorful-json 1.1.0 
html-head-snippets 0.2.0 
html-tag-auto-complete 2.1.0 
html-to-css 0.2.2 
html-to-less 1.2.2 
ide-html 0.6.2 
ide-json 0.2.1 
json-to-html 0.2.4 
pretty-html 1.0.0 
pretty-json 2.1.2 
teletype 0.13.4 
```
